#!/usr/bin/ruby
#
# This file is part of CPEE-FRAMES.
#
# CPEE-FRAMES is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# CPEE-FRAMES is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# CPEE-FRAMES (file LICENSE in the main directory). If not, see
# <http://www.gnu.org/licenses/>.

if File.exists?(File.join(__dir__,'..','lib','cpee-frames','implementation.rb'))
  require_relative File.join(__dir__,'..','lib','cpee-frames','implementation')
else
  require 'cpee-frames/implementation'
end

options = {
  :host => 'localhost',
  :port => 8305,
  :secure => false
}

Riddl::Server.new(CPEE::Frames::SERVER, options) do
  accessible_description true
  cross_site_xhr true

  @riddl_opts[:data_dir] ||= File.join(__dir__,'data')

  use CPEE::Frames::implementation(@riddl_opts)
end.loop!
